kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
  namespace: monitoring
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-client-provisioner
          image: 10.204.209.253/common/nfs-client-provisioner:1.0
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 10.204.51.64
            - name: NFS_PATH
              value: /app/nfs/prometheus/
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.204.51.64
            path: /app/nfs/prometheus/
